"""Broad chemistry taxonomy used when no topic-specific profile is selected."""

rules = [
    ("organic products", "product", ["organic product", "target molecule", "synthesis product"]),
    ("heterocycles", "product", ["heterocycle", "heterocyclic compound"]),
    ("pharmaceutical compounds", "product", ["drug candidate", "pharmaceutical", "bioactive molecule"]),
    ("small-molecule substrates", "substrate", ["small molecule substrate", "organic substrate"]),
    ("aromatic substrates", "substrate", ["arene", "aromatic substrate", "heteroarene"]),
    ("biomolecular substrates", "substrate", ["protein", "peptide", "nucleic acid", "biomolecule"]),
    ("propargylic alcohols", "substrate", ["propargylic alcohol", "propargyl alcohol", "ethynyl tertiary alcohol", "ethynyl tertiary alcohols", "alkynyl tertiary alcohol", "alkynyl tertiary alcohols", "azaarylethynyl tertiary alcohol", "azaarylethynyl tertiary alcohols"]),
    ("activated propargylic derivatives", "substrate", ["propargylic alcohol derivative", "propargylic alcohol derivatives", "propargylic carbonate", "propargylic carbonates", "propargylic mesylate", "propargylic mesylates", "propargylic phosphate", "propargylic phosphates", "propargylic acetate", "propargylic acetates", "propargylic benzoate", "propargylic benzoates", "propargylic carbamate", "propargylic carbamates", "propargylic ester", "propargylic esters", "propargylic halide", "propargylic halides", "propargylic substrate", "propargylic substrates"]),
    ("terminal alkynes", "substrate", ["terminal alkyne", "1-alkyne", "1-alkynes"]),
    ("conjugated enynes", "substrate", ["conjugated enyne", "1,3-enyne", "1,3-enynes"]),
    ("enol triflates", "substrate", ["enol triflate", "enol triflates", "vinyl triflate", "vinyl triflates"]),
    ("rearrangement precursors", "substrate", ["propargyl claisen rearrangement", "propargylic claisen rearrangement", "myers allene synthesis", "propargylic rearrangement precursor"]),
    ("transition-metal catalysis", "catalyst_or_method", ["transition metal catalyst", "metal-catalyzed", "metal catalysis"]),
    ("organocatalysis", "catalyst_or_method", ["organocatalyst", "organocatalysis"]),
    ("photochemical methods", "catalyst_or_method", ["photocatalysis", "photoredox", "visible light", "photochemical"]),
    ("electrochemical methods", "catalyst_or_method", ["electrochemical", "electrocatalysis", "electrosynthesis"]),
    ("enzymatic methods", "catalyst_or_method", ["enzyme", "enzymatic", "biocatalysis"]),
    ("computational methods", "catalyst_or_method", ["machine learning", "neural network", "computational", "simulation", "density functional theory"]),
    ("organoboron reagents", "organometallic_partner", ["boronic acid", "boronate", "organoboron"]),
    ("organomagnesium reagents", "organometallic_partner", ["grignard", "organomagnesium"]),
    ("organolithium reagents", "organometallic_partner", ["organolithium", "alkyllithium"]),
    ("chiral ligands", "ligand_or_chiral_source", ["chiral ligand", "asymmetric ligand"]),
    ("chiral catalysts", "ligand_or_chiral_source", ["chiral catalyst", "asymmetric catalyst"]),
    ("halide leaving groups", "leaving_group", ["chloride", "bromide", "iodide", "halide leaving group"]),
    ("sulfonate leaving groups", "leaving_group", ["tosylate", "mesylate", "sulfonate leaving group"]),
    ("cross-coupling", "reaction_type", ["cross-coupling", "coupling reaction"]),
    ("addition reactions", "reaction_type", ["addition reaction", "hydrofunctionalization"]),
    ("substitution reactions", "reaction_type", ["substitution reaction", "nucleophilic substitution"]),
    ("oxidation and reduction", "reaction_type", ["oxidation", "reduction", "redox reaction"]),
    ("cyclization and annulation", "reaction_type", ["cyclization", "annulation", "cycloaddition"]),
    ("primary research article", "document_scope", ["research article", "original research", "full paper"]),
    ("review article", "document_scope", ["review article", "systematic review", "comprehensive review"]),
    ("mechanistic study", "document_scope", ["mechanistic study", "mechanism investigation"]),
    ("computational study", "document_scope", ["computational study", "in silico study", "modeling study"]),
]
